[project]
name = "listing-bot"
version = "0.1.0"
description = "A listing bot to list your hypixel accounts!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3.0",
    "py-cord>=2.6.1",
    "requests>=2.32.5",
]
